CREATE TABLE "administrators"
(
    "admin_id"       INTEGER      NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "admin_name"     VARCHAR(125) NOT NULL,
    "admin_surname"  VARCHAR(125) NOT NULL,
    "admin_email"    VARCHAR(50)  NOT NULL,
    "admin_phone"    VARCHAR(50)  NOT NULL,
    "admin_password" VARCHAR(25)  NOT NULL,
    "admin_role"     VARCHAR(25)  NOT NULL DEFAULT 'ROLE_ADMIN',
    "user_id"        INTEGER
);
COMMENT ON TABLE "administrators" IS 'Управление билетами, пользователями, заказами.';


CREATE TABLE "users"
(
    "user_id"       INTEGER      NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "user_name"     VARCHAR(125) NOT NULL,
    "user_surname"  VARCHAR(125) NOT NULL,
    "user_email"    VARCHAR(50)  NOT NULL,
    "user_phone"    VARCHAR(50)  NOT NULL,
    "user_password" VARCHAR(25)  NOT NULL,
    "user_role"     VARCHAR(25)  NOT NULL DEFAULT 'ROLE_USER',
    "order_id"      INTEGER
);
COMMENT ON TABLE "users" IS 'Просмотр и бронирование билетов, оплата заказов.';


CREATE TABLE "orders"
(
    "order_id"         INTEGER      NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "order_title"      VARCHAR(50)  NOT NULL,
    "order_info"       VARCHAR(255) NOT NULL,
    "order_created_at" TIMESTAMP    NOT NULL,
    "order_amount"     DECIMAL      NOT NULL,
    "order_state"      VARCHAR(25)  NOT NULL,
    "ticket_id"        INTEGER,
    "payment_id"       INTEGER
);
COMMENT ON TABLE "orders" IS 'Cодержит информацию о пользователе, билете, статусе оплаты.';


CREATE TABLE "tickets"
(
    "ticket_id"          INTEGER       NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "ticket_title"       VARCHAR(50)   NOT NULL,
    "ticket_description" VARCHAR(1000) NOT NULL,
    "ticket_price"       DECIMAL       NOT NULL,
    "ticket_discount"    DECIMAL,
    "ticket_image_path"  VARCHAR(255)  NOT NULL
);
COMMENT ON TABLE "tickets" IS 'Содержит данные о маршруте, стоимости.';



CREATE TABLE "payments"
(
    "payment_id"         INTEGER      NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "payment_info"       VARCHAR(255) NOT NULL,
    "payment_created_at" TIMESTAMP    NOT NULL
);
COMMENT ON TABLE "payments" IS 'Содержит данные о маршруте, стоимости.';


-- ALTER TABLE "administrators"
--     ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id")
--         ON UPDATE NO ACTION ON DELETE NO ACTION;
-- ALTER TABLE "users"
--     ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id")
--         ON UPDATE NO ACTION ON DELETE NO ACTION;
-- ALTER TABLE "orders"
--     ADD FOREIGN KEY ("ticket_id") REFERENCES "tickets" ("ticket_id")
--         ON UPDATE NO ACTION ON DELETE NO ACTION;
-- ALTER TABLE "orders"
--     ADD FOREIGN KEY ("payment_id") REFERENCES "payments" ("payment_id")
--         ON UPDATE NO ACTION ON DELETE NO ACTION;
